language: python
sudo: false
notifications:
  email: false
env:
  global:
    - TZ=UTC
python:
  - 2.7
  - pypy
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
script:
  nosetests --rednose --with-cov
after_success:
  codecov
